# -*- mode: ruby -*-
# vi: set ft=ruby :

domain = 'example.com'

puppet_nodes = [
  {:hostname => 'learnpup',  :ip => '172.16.32.20', :box => 'learning_puppet_vm',
    :fwdhost1 => 20443, :fwdguest1 => 443, :fwdhost2 => 20080, :fwdguest2 => 80, 
    :fwdhost3 => 20090, :fwdguest3 => 90, 
    :ram => 4096
  },
]

Vagrant.configure("2") do |config|
  puppet_nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = node[:box]
      # node_config.vm.box_url = 'http://files.vagrantup.com/' + node_config.vm.box + '.box'
      node_config.vm.hostname = node[:hostname] + '.' + domain
      node_config.vm.network :private_network, ip: node[:ip]
      # node_config.vm.network :public_network, ip: node[:ip]

      if false
      end
      if node[:fwdhost1]
        node_config.vm.network :forwarded_port, guest: node[:fwdguest1], host: node[:fwdhost1]
      end
      if node[:fwdhost2]
        node_config.vm.network :forwarded_port, guest: node[:fwdguest2], host: node[:fwdhost2]
      end
      if node[:fwdhost3]
        node_config.vm.network :forwarded_port, guest: node[:fwdguest3], host: node[:fwdhost3]
      end

      memory = node[:ram] ? node[:ram] : 256;
      node_config.vm.provider :virtualbox do |vb|
        vb.customize [
          'modifyvm', :id,
          '--name', node[:hostname],
          '--memory', memory.to_s
        ]
      end

      # node_config.vm.provision :puppet do |puppet|
      #   puppet.manifests_path = 'provision/manifests'
      #   puppet.module_path = 'provision/modules'
      # end
    end
  end
end
